server {
    listen 127.0.0.1:8080;
    server_name one hello;
    root www ;
    client_max_body_size 2000000;

    location / {
        index cloe.html;
        autoindex off;
    }

	location /images/ {
		index image.html;
        autoindex off;
        redirect http://42perpignan.fr/;
	}

	location /uploads/ {
        index upload.html;
		methods GET POST DELETE;
	}

    location /public/ {
        index public.html;
        methods GET POST DELETE;
	}

    location /autoindex/ {
        index notexsisted.html;
        autoindex on;
    }

    location /cgi-bin/ {
        index form.html;
        cgi_pass /usr/bin/python3;
        methods GET POST;
    }

	location /cgi-bin/bash/
	{
		cgi_pass /bin/bash;
		methods GET POST DELETE;
	}

    location /cgi-bin/perl/
	{
        cgi_pass /usr/bin/perl;
	}
    error_page 400 /error/400-v0.html;
    error_page 403 /error/403.html;
	error_page 404 /error/404.html;
    error_page 405 /error/405-v0.html;
    error_page 500 /error/500.html;
    error_page 501 /error/501.html;
}

server {
    listen 127.0.0.1:8081;
    server_name two hello;
    root www ;
    client_max_body_size 1000000;

    location / {
        index theo.html;
        autoindex off;
    }

	location /images/ {
		index image.html;
        autoindex off;
        redirect http://42perpignan.fr/;
	}

	location /uploads/ {
        index upload.html;
		methods GET POST DELETE;
	}

    location /public/ {
        index public.html;
        methods GET POST DELETE;
        redirect /uploads;
	}

    location /cgi-bin/ {
        cgi_pass /usr/bin/python3;
        methods GET POST;
    }
	location /cgi-bin/bash/
	{
		cgi_pass /bin/bash;
		methods GET POST DELETE;
	}
    location /cgi-bin/perl/
	{
        cgi_pass /usr/bin/perl;
	}
    error_page 400 /error/400-v0.html;
    error_page 403 /error/403.html;
	error_page 404 /error/404.html;
    error_page 405 /error/405-v0.html;
    error_page 500 /error/500.html;
    error_page 501 /error/501.html;
}