server {
    listen 127.0.0.1:8080;
    server_name number_one hello;
    root www ;
    client_max_body_size 1000000 ;
    location / {
        index cloe.html;
        autoindex off;
        methods GET POST DELETE;
    }
	location /images/ {
		index image.html;
        autoindex on;
        methods GET POST;
	}

	location /uploads/ {
        index upload.html;
		methods GET;
	}

    location /public/ {
        index public.html;
        methods GET POST DELETE;
        redirect /uploads;
	}

    location /cgi-bin/ {
        cgi_pass /usr/bin/python3;
        methods GET POST;
    }

    error_page 400 /error/400-v0.html;
    error_page 403 /error/403.html;
	error_page 404 /error/404.html;
    error_page 405 /error/405-v0.html;
    error_page 500 /error/500-v0.html;
    error_page 501 /error/501-v0.html;
}
