
# server {
#     listen 127.0.0.1:8080;
#     # listen 8081;
#     server_name server1;
#     root ./www;
#     # client_max_body_size 50000; # => Theo it doesn't take any info!!!


#     location / {                # direction root '/' marche!
#         methods GET;            # je comprends pas si je ne met pas methods dans 1st ligne, ca march pas!?  
# 		index index.html;     # => Theo it doesn't stock address of index (par example "index.html" ou "folder/index.html")
#         # autoindex on;
#         # cgi_pass hello.py;
#         redirect images/;    # Directive //it is invalid.
#     }

#     # location /cgi-bin/ {
#     #     cgi_pass ./www/cgi-bin/script.py;
#     #     methods GET POST DELETE;
#     # }

#     # location /images/ {
#     #     methods GET POST;
#     #     index /index.html;
#     #     redirect /uploads;
#     # }

#     # location /uploads/ {
#     #     methods POST;
#     #     root /www/uploads;
#     # }

#     error_page 404 /error/404.html; //it works! bravo
#     error_page 405 /error/405.html;
#     error_page 403 /error/403.html;
# }

# # server {
# #     listen 0.0.0.0:8082;
# #     server_name server2;
# #     location / {
# #         root ./tests;
# #         index index.html;
# #         autoindex off;
# #     }

# #     location /images/ {
# #         root ./assets;
# #         autoindex on;
# #     }

# #     error_page 500 error/500.html;
# # }

# server {
#     listen 8000;
#     server_name server3;
#     location / {
#         root /www
#         index index.html;
#         autoindex on;
#     }
# }

server {
    listen 127.0.0.1:8080;
    listen 8081;
    server_name server1;
    root www;

    location / {
        index theo.html;
        autoindex on;
        methods GET;
    }

    location /cgi-bin/ {
        cgi_pass script.py;
        methods GET POST DELETE;
    }

    location /images/ {
        methods GET POST;
        index index.html;

    }

    location /uploads/ {
        methods POST;
    }

    error_page 404 /404.html;
    error_page 405 /405.html;
    error_page 403 /403.html;
}

server {
    listen 0.0.0.0:8082;
    server_name server2;
    location / {
        root ./tests;
        index index.html;
        autoindex off;
    }

    location /images/ {
        root ./assets;
        autoindex on;
    }

    error_page 500 /500.html;
}

server {
    listen 8000;
    server_name server3;

    location / {
        root www;
        index index2.html;
        autoindex on;
        methods GET POST;
    }
}