
server {
    listen 127.0.0.1:8080;
    listen 8081;
    server_name server1;
    root /www;
    index index.html;

    location / {
        index index2.html;
        autoindex on;
        methods GET POST DELETE;
    }

    location /cgi-bin/ {
        cgi_pass ./cgi-bin/script.py;
        methods GET POST DELETE;
    }

    location /new/ {
        methods GET POST;

    }

    

    error_page 404 error_page/404.html;
}

server {
    listen 0.0.0.0:8082;
    server_name server2;

    location / {
        root ./tests;
        index index.html;
        autoindex off;
    }

    location /images/ {
        root ./assets;
        autoindex on;
    }

    error_page 500 /500.html;
}

server {
    listen 8000;
    server_name server3;

    location / {
        root /www
        index index.html;
        autoindex on;
    }
}