server {
    listen 8181;
    server_name example.com;
    root www ;

    location / {
        index server1.html;
        autoindex off;
    }

	error_page 404 /error/404.html;
}

server {
    listen 0.0.0.0:8282;
    server_name server_two;
    root www ;

    location / {
        index server2.html;
        autoindex off;
    }

	error_page 404 /error/404.html;
}


server {
    listen 127.0.0.1:8080;
    server_name server_three;
    root www ;

    location / {
        index server3.html;
        autoindex off;
    }
    
	error_page 404 /error/404.html;
}