
server {
    listen 8080;
    server_name localhost;

    location / {
        root ./www;
        index index.html;
        autoindex on;
    }

    location /cgi-bin/ {
        cgi_pass ./cgi-bin/script.py;
    }

    error_page 404 /404.html;
}

server {
    listen 8081;
    server_name test.local;

    location / {
        root ./tests;
        index index.html;
        autoindex off;
    }

    location /images/ {
        root ./assets;
        autoindex on;
    }

    error_page 500 /500.html;
}
