# Configuration minimum


http {
    server {
        listen 8080;
        server_name localhost;

        root ./www;
        index index.html;

        location / {
            methods GET;
        }
    }
}


# # Configuration example

# http {
#     include mime.types;
#     client_max_body_size 10M;

#     server {
#         listen 8080;
#         server_name localhost;

#         root ./www;
#         index index.html;

#         error_page 404 /errors/404.html;
#         error_page 500 /errors/500.html;

#         location / {
#             autoindex off;
#             methods GET POST;
#         }

#         location /uploads {
#             root ./www/uploads;
#             autoindex on;
#             methods GET POST DELETE;
#         }

#         location /cgi-bin {
#             cgi_pass /usr/bin/python3;
#             root ./www/cgi-bin;
#             methods GET POST;
#         }
#     }

#     # Second server block
#     server {
#         listen 9090;
#         server_name example.com;

#         root ./site_example;
#         index home.html;

#         location / {
#             autoindex off;
#             methods GET;
#         }

#         location /images {
#             root ./site_example/images;
#             autoindex on;
#             methods GET;
#         }
#     }
# }
